create database Business_Context
use [Business_Context]
--DATA PREPARATION AND UNDERSTANDING
--01 What is the total number of rows in each of the 3 tables in the database?

select
    (select count(*) from dbo.Customer) as Customer_row_count,
    (select count(*) from dbo.prod_cat_info) as prod_cat_info_row_count,
    (select count(*) from dbo.Transactions) as Transactions_row_count;

--02. What is the total number of transactions that have a return?
select count(*) AS total_returned_transactions
  FROM dbo.Transactions
  WHERE  [total_amt] like '-%';

/* 03. As you would have noticed, the dates provided across the datasets are not in a
correct format. As first steps, pls convert the date variables into valid date formats
before proceeding ahead.*/
select FORMAT(DOB,'dd-MM-yyyy') as formatted_date from [dbo].[Customer]
select FORMAT(tran_date,'dd-MM-yyyy') as formatted_date from [dbo].[Transactions]

/*  04. What is the time range of the transaction data available for analysis? Show the
output in number of days, months and years simultaneously in different columns.  */

select 
datediff(day,min(tran_date),max(tran_date)) as days,
datediff(month,min(tran_date),max(tran_date)) as months,
datediff(year,min(tran_date),max(tran_date)) as years
from [dbo].[Transactions];


--05. Which product category does the sub-category “DIY” belong to?
select [prod_cat] FROM [dbo].[prod_cat_info] where [prod_subcat] = 'DIY'

--DATA ANALYSIS
--01. Which channel is most frequently used for transactions?
select top 1 [Store_type] ,count([Store_type]) as channel from [dbo].[Transactions]
group by [Store_type]
ORDER BY channel desc;

--02. What is the count of Male and Female customers in the database?
select Gender,count(Gender)as count from [dbo].[Customer] where Gender in ('M','F')
group by Gender

--03. From which city do we have the maximum number of customers and how many?
select top 1 [city_code],count([city_code]) as no_of_cus from [dbo].[Customer]
group by [city_code]
order by no_of_cus desc;

--04. How many sub-categories are there under the Books category?
select [prod_cat],count([prod_subcat]) as no_subcat from [dbo].[prod_cat_info] where [prod_cat] = 'Books' 
group by [prod_cat]

--05. What is the maximum quantity of products ever ordered?
select max([Qty]) as maximum_qty
from [dbo].[Transactions] 

--06. What is the net total revenue generated in categories Electronics and Books?
select [prod_cat],sum([total_amt]) as tot_revenue 
from [dbo].[prod_cat_info] p
inner join [dbo].[Transactions] t on p.[prod_cat_code] = t.[prod_cat_code] and t.prod_subcat_code=p.prod_sub_cat_code
where [prod_cat] in ('Electronics','Books')
group by [prod_cat];

--07. How many customers have >10 transactions with us, excluding returns?

 select count([customer_Id]) as cust_count
from [dbo].[Customer] where [customer_Id] in 
( select [customer_Id] from [dbo].[Transactions] t
inner join [dbo].[Customer] c on t.cust_id=c.customer_Id
where [total_amt] not like'-%'
group by [customer_Id]
having count([transaction_id]) > 10);

/*08. What is the combined revenue earned from the “Electronics” & “Clothing”
categories, from “Flagship stores”?*/

SELECT SUM(total_amt) AS CombinedRevenue
FROM Transactions t
inner join [dbo].[prod_cat_info] p on t.[prod_cat_code]= p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
WHERE [prod_cat] IN ('Electronics', 'Clothing') AND store_type = 'Flagship store'


/*9. What is the total revenue generated from “Male” customers in “Electronics”
category? Output should display total revenue by prod sub-cat.*/

SELECT [Gender],p.[prod_cat], p.[prod_subcat],
       SUM(total_amt) AS TotalRevenue_Male
FROM Transactions t
inner JOIN [dbo].[prod_cat_info] p ON t.[prod_cat_code] = p.[prod_cat_code] and t.[prod_subcat_code] = p.[prod_sub_cat_code]
inner JOIN [dbo].[Customer] c ON t.[cust_id] = c.[customer_Id]
WHERE p.[prod_cat] = 'Electronics' and Gender =  'M'
GROUP BY [Gender],p.[prod_cat], p.[prod_subcat] ;

/*10. What is percentage of sales and returns by product sub category; display only top
5 sub categories in terms of sales?*/
 
select top 5 p.[prod_subcat],(sum([total_amt])/(select sum([total_amt])
from [dbo].[Transactions]))*100 as percentage_of_sales,
(count(case when [total_amt]<0 then [total_amt] else null
end)/sum([total_amt]))*100 as percent_of_return
from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on t.[prod_subcat_code]=p.[prod_sub_cat_code] and t.prod_cat_code = p.prod_cat_code 
group by p.[prod_subcat]
order by sum([total_amt]) desc;

/*11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these consumers in last 30 days of transactions from max transaction
date available in the data?*/

SELECT [cust_id],sum([total_amt]) AS TOTAL_REVENUE
FROM [dbo].[Transactions]
where [cust_id] in 
(  SELECT [customer_Id] FROM [dbo].[Customer]
WHERE DATEDIFF(YEAR,CONVERT(DATE,[DOB],103),GETDATE()) between 25 and 35
and CONVERT(date,[tran_date],103) between DATEADD(day,-30, (select max(convert(DATE,[tran_date],103)) FROM [dbo].[Transactions]))
AND (select max(convert(DATE,[tran_date],103)) FROM [dbo].[Transactions]))
GROUP BY [cust_id]


/*12. Which product category has seen the max value of returns in the last 3 months of
transactions?*/

select top 1 
prod_cat,sum(total_amt) as totalamt
from
prod_cat_info p
inner join  Transactions t on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where [total_amt] <0 and CONVERT(date,tran_date,103) between DATEADD(month,-3, (select max(convert(date,tran_date,103)) FROM Transactions))
AND (select max(convert(date,tran_date,103)) FROM Transactions)
group by
prod_cat
order by totalamt desc;

/*13. Which store-type sells the maximum products; by value of sales amount and by
quantity sold?*/
select top 1 [Store_type], sum([total_amt]) as sales_amt,sum([Qty]) as qty
from [dbo].[Transactions]
group by [Store_type]
order by [Qty] desc; 

--14. What are the categories for which average revenue is above the overall average.
select [prod_cat],avg([total_amt]) as total_rev
from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on t.prod_subcat_code=p.prod_sub_cat_code and t.prod_cat_code = p.prod_cat_code
group by [prod_cat]
having avg([total_amt]) > (select avg([total_amt]) from [dbo].[Transactions])

/*15. Find the average and total revenue by each subcategory for the categories which
are among top 5 categories in terms of quantity sold.*/

SELECT top 5 [prod_cat], [prod_subcat],
avg([total_amt]) as avg_revenue,
SUM([total_amt]) AS total_quantity_sold
FROM [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on t.[prod_cat_code]=p.[prod_cat_code] and t.prod_subcat_code=p.prod_sub_cat_code
where [prod_cat] in
( select top 5 [prod_cat] from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on t.[prod_cat_code]=p.[prod_cat_code] and t.prod_subcat_code=p.prod_sub_cat_code
group by [prod_cat]
order by sum([Qty]) desc)
group by [prod_cat], [prod_subcat]


 